// src/data.js
export const sections = [
  {
    id: "team",
    title: "Customar Services Excellence",
    image: "b1.PNG",
    heading: "Phone Etiquette",
    description: "Covers specific strategies and techniques agents use to maintain a polite and professional tone during customer interactions, ensuring a positive customer experience.",
    toolsTitle: "Issue Resolution",
    toolsDesc: "Delves into the process of addressing customer concerns efficiently and effectively, including steps such as active listening, proposing solutions, and following up for satisfaction.",
  },
  {
    id: "customer",
    title: "Lead Genration strateies",
    image: "b2.PNG",
    heading: "Issue Resolution",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "chat support",
    title: "Chat Support Best Prectice",
    image: "b3.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "teem colloboration",
    title: "Teem Colloboration",
    image: "b4.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "leed genation",
    title: "Lead Genration strateies",
    image: "b5.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "lead strateies",
    title: "Lead Genration strateies",
    image: "b6.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "lead",
    title: "Lead Genration strateies",
    image: "b1.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
  {
    id: "strateies",
    title: "Lead Genration strateies",
    image: "b2.PNG",
    heading: "Customer Support",
    description: "Providing exceptional service to retain clients and ensure satisfaction.",
    toolsTitle: "Support Tools",
    toolsDesc: "Live chat, help desk, and CRM systems enhance support quality.",
  },
 
];
